# main.py

from typing import Dict, List

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from backend.conservation import analyze_site, rank_sites, structural_score_from_crack_detection


# ============================================================
# FASTAPI
# ============================================================

app = FastAPI(
    title="HeritageGuard Conservation Intelligence API",
    description="Member 5 - Conservation Intelligence Module",
    version="1.2",
)

# Allows the team's frontend (React/Streamlit/etc.) to call this API
# directly during development. Tighten allow_origins before deployment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# MEMBER 6 API
# ============================================================

# Change this to Member 6's actual API address, e.g.:
# http://localhost:8001/predict-risk
MEMBER6_API_URL = "http://localhost:8001/predict-risk"
MEMBER6_TIMEOUT_SECONDS = 10


# ============================================================
# INPUT SCHEMA
# (field names match ml_ready_temporal_2024_to_2025.csv, Member 1's dataset)
# ============================================================

class SiteData(BaseModel):
    site_id: str

    # Prediction generated by Member 6's model. Required on every call —
    # this module doesn't compute it, only interprets it.
    predicted_risk: float = Field(
        ge=0, le=100, description="Predicted deterioration risk from Member 6"
    )

    # --- Environmental (Member 1) ---
    humidity_pct: float = Field(ge=0, le=100)
    annual_rainfall_mm: float = Field(ge=0)
    air_quality_index: float = Field(ge=0)
    extreme_weather_events_count: int = Field(ge=0)

    # --- Visitor pressure (Member 1) ---
    annual_visitor_count: int = Field(ge=0)
    vandalism_incidents_count: int = Field(ge=0)

    # --- Site vulnerability (Member 1 / Member 2) ---
    flood_risk_score: float = Field(ge=0)
    seismic_zone_rating: int = Field(ge=1, le=5)
    proximity_to_industrial_area_km: float = Field(ge=0)
    vegetation_cover_pct: float = Field(ge=0, le=100)

    # From Member 3's computer-vision crack-detection module. If you only
    # have her raw crack_count/crack_area_ratio output, call
    # POST /conservation/structural-score first to convert it.
    structural_score: float = Field(ge=1, le=5)


class CrackDetectionResult(BaseModel):
    """Exact output shape of Member 3's detect_cracks()."""
    crack_count: int = Field(ge=0)
    crack_area_ratio: float = Field(ge=0)
    average_confidence: float = Field(ge=0, le=1)
    max_confidence: float = Field(ge=0, le=1)


class WhatIfRequest(BaseModel):
    site: SiteData

    # Example:
    #   {"annual_visitor_count": 700000}
    #   {"humidity_pct": 70, "annual_visitor_count": 700000}
    changes: Dict[str, float]


ALLOWED_WHAT_IF_FIELDS = {
    "humidity_pct", "annual_rainfall_mm", "air_quality_index",
    "extreme_weather_events_count", "annual_visitor_count",
    "vandalism_incidents_count", "flood_risk_score", "seismic_zone_rating",
    "proximity_to_industrial_area_km", "vegetation_cover_pct",
}


# ============================================================
# ROOT
# ============================================================

@app.get("/")
def home():
    return {"module": "Conservation Intelligence", "status": "running"}


# ============================================================
# CONVERT MEMBER 3's CRACK DETECTION -> structural_score
# ============================================================

@app.post("/conservation/structural-score")
def structural_score(crack_result: CrackDetectionResult):
    """
    Bridge endpoint: feed in the exact dict Member 3's detect_cracks()
    returns, get back the 1-5 structural_score this module uses.
    """
    return {
        "structural_score": structural_score_from_crack_detection(crack_result.model_dump())
    }


# ============================================================
# ANALYZE A SINGLE SITE
# ============================================================

@app.post("/conservation/analyze")
def analyze(site: SiteData):
    try:
        return analyze_site(site.model_dump())
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


# ============================================================
# ANALYZE + RANK A BATCH OF SITES
# (powers a "which sites need attention first" dashboard view)
# ============================================================

@app.post("/conservation/rank")
def rank(sites: List[SiteData]):
    if not sites:
        raise HTTPException(status_code=400, detail="Provide at least one site.")
    try:
        return rank_sites([s.model_dump() for s in sites])
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


# ============================================================
# WHAT-IF INTERVENTION ANALYSIS
# ============================================================

@app.post("/conservation/what-if")
async def what_if(request: WhatIfRequest):
    site = request.site.model_dump()
    changes = request.changes

    # --------------------------------------------------------
    # Validate changes
    # --------------------------------------------------------
    invalid_fields = set(changes) - ALLOWED_WHAT_IF_FIELDS
    if invalid_fields:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid intervention field(s): {', '.join(sorted(invalid_fields))}",
        )

    # --------------------------------------------------------
    # Build the modified site
    # --------------------------------------------------------
    modified_site = {**site, **changes}

    # --------------------------------------------------------
    # Ask Member 6's ML model for the new prediction
    # --------------------------------------------------------
    try:
        async with httpx.AsyncClient(timeout=MEMBER6_TIMEOUT_SECONDS) as client:
            response = await client.post(MEMBER6_API_URL, json=modified_site)
            response.raise_for_status()
            prediction = response.json()
    except httpx.HTTPError as e:
        raise HTTPException(
            status_code=503,
            detail=f"Could not connect to Member 6 prediction service: {str(e)}",
        )

    if "predicted_risk" not in prediction:
        raise HTTPException(
            status_code=502,
            detail="Member 6 prediction service response missing 'predicted_risk'.",
        )

    modified_site["predicted_risk"] = prediction["predicted_risk"]

    # --------------------------------------------------------
    # Recompute the FULL conservation picture for the scenario —
    # risk, priority score/level, and recommendations all update to
    # reflect the "what if" scenario, not just the raw risk number.
    # --------------------------------------------------------
    try:
        original_analysis = analyze_site(site)
        scenario_analysis = analyze_site(modified_site)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    risk_change = round(
        scenario_analysis["predicted_risk"] - original_analysis["predicted_risk"], 2
    )
    priority_score_change = round(
        scenario_analysis["priority_score"] - original_analysis["priority_score"], 2
    )

    if risk_change < 0:
        interpretation = "The intervention scenario reduces the predicted deterioration risk."
    elif risk_change > 0:
        interpretation = "The intervention scenario increases the predicted deterioration risk."
    else:
        interpretation = "The intervention scenario produces no change in predicted deterioration risk."

    return {
        "site_id": site["site_id"],
        "changes_applied": changes,
        "original": {
            "predicted_risk": original_analysis["predicted_risk"],
            "priority_score": original_analysis["priority_score"],
            "priority_level": original_analysis["priority_level"],
        },
        "scenario": {
            "predicted_risk": scenario_analysis["predicted_risk"],
            "priority_score": scenario_analysis["priority_score"],
            "priority_level": scenario_analysis["priority_level"],
            "recommendations": scenario_analysis["recommendations"],
        },
        "risk_change": risk_change,
        "priority_score_change": priority_score_change,
        "interpretation": interpretation,
    }